language: c

sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - python3
      - ninja-build

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install meson; fi

script:
  - scripts/meson-test.sh
